name: Pipeline
on: push
jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: |
          cd module-b
          mvn clean install
      - run: |
          cd module-a
          mvn clean install
      - run: mvn checkstyle:check

  build:
    needs: [code-analysis]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn package
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t annaburlachuk/practice5:latest .
          docker push annaburlachuk/practice5:latest